name: Scheduled build
on:
  schedule:
  - cron: '15 16 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger our build webhook on Render
      run: curl -s -X POST "https://api.render.com/deploy/${TOKEN}"
      env:
        TOKEN: ${{ secrets.RENDER_CRON_BUILD_HOOK }}
